### ISSUE TITLE
Blank page after installing contao-bootstrap

### ISSUE THREAD

**Issue by septentrio** [contao-bootstrap/bundle#1]
Hello,

As i wanted to update an old contao website to handle mobile features, i upgraded the installation from 3.06 to Contao 3.2, i then installed composer and contao-bootstrap, made the proper db updates.

However, once installed when i do a preview of my site, i've only got my header tags loaded and no conent is displayed.

Any clue ?

**Comment by dmolineus** [comment]
This issue tracker is meant for bugs and feature request. Please use the forum for support questions. https://community.contao.org/de/
