### ISSUE TITLE
Change version format to LGPL-3.0-or-later

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/bundle#10]
add compatibility for Contao 4.4 - maybe 4.5

it´s not possible to install per Contao manager :(

change license at composer.json to `LGPL-3.0-or-later`

**Comment by dmolineus** [comment]
The bundle in version 2 is compatible with Contao 4. What are your refering to?

**Comment by zonky2** [comment]
Contao manager present label "incomaptible" with C4.4 and C4.5

**Comment by dmolineus** [comment]
Hm, seems like the contao manager / package indexer changed. It was possible, I did it a couple of times. Could you open a ticket here please https://github.com/contao/contao-manager/issues

The issue occurs probably because the package is a metapackage.

**Comment by dmolineus** [comment]
Related https://github.com/contao/contao-manager/issues/135

**Comment by zonky2** [comment]
I updated this issue...

**Comment by dmolineus** [comment]
Funktioniert nun wieder.

**Comment by zonky2** [comment]
das `LGPL-3.0-or-later` sollte m.E. trotzdem für packagist.org geändert werden...

**Comment by dmolineus** [comment]
Ja, fehlt beim Bundle noch.
