### ISSUE TITLE
TemplateParseListener Exception bei selbst entwickeltem FronEndModul

### ISSUE THREAD

**Issue by felix-kaestner** [contao-bootstrap/bundle#11]
In einem Projekt verwende ich ein eigenes FrontEnd Module welches ich innerhalb eines Bundles in die Contao Installation lade. (Das Bundle steht nicht auf packagist zur Verfügung und wird momentan noch selbstständig via composer eingebunden). Desweiteren wollte ich für das Projekt das Contao-Bootstrap Bundle verwenden. Leider komme ich zu einem Fehler. 
Sobald ich nun ein eigenes FrontEndModul verwende bekomme ich folgenden Fehlermeldung im Log:

```
[2018-10-16 12:12:29] request.INFO: Matched route "contao_frontend". {"route":"contao_frontend","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_scope":"frontend","alias":"home","_route":"contao_frontend"},"request_uri":"http://localhost/home.html","method":"HEAD"} []
[2018-10-16 12:12:29] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2018-10-16 12:12:29] request.INFO: Matched route "contao_frontend". {"route":"contao_frontend","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_scope":"frontend","alias":"home","_route":"contao_frontend"},"request_uri":"http://localhost/home.html","method":"GET"} []
[2018-10-16 12:12:29] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2018-10-16 12:12:29] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 2 passed to ContaoBootstrap\\Core\\Listener\\TemplateParseListener::parse() must be of the type string, null given, called in /var/www/html/vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php on line 61 at /var/www/html/vendor/contao-bootstrap/core/src/Listener/TemplateParseListener.php:79)"} []
```

Offensichtlich wird das Template des FrontEndModuls nicht erkannt. Allerdings wird das Template sowohl als Variable ```strTemplate``` und dann nochmals in der ```compile()```-Funktion über ```$this->Template->setName()``` gesetzt. Zudem wird mit das richtige Template entsprechend ohne das Vorhandensein des Contao-Bootstrap-Bundles auf der Webseite ausgegeben und es kommt zu keiner Fehlermeldung.
Ich hoffe sie können mir weiter helfen.

Der Quellcode des Bundles ist unter https://github.com/markenzoo/material-theme-bundle einzusehen.
Es wird Contao 4.4 verwendet.

**Comment by dmolineus** [comment]
Hint: 
https://github.com/markenzoo/material-theme-bundle/blob/219e10c63173957d247197f6eb76986cc3764299/material-theme-bundle/src/Resources/contao/modules/NavBarModule.php#L63

Wobei es mit https://github.com/markenzoo/material-theme-bundle/blob/219e10c63173957d247197f6eb76986cc3764299/material-theme-bundle/src/Resources/contao/modules/NavBarModule.php#L64 egal sein sollte.

Das Contao Modul initialisiert das Template-Objekt übrigens selbst, sodass die Zeile obsolet wird.

**Comment by felix-kaestner** [comment]
Ja das ist richtig. Deshalb sollte das Template bereits erkannt werden, sobald die Variable strTemplate in der Klasse deklariert wird, da daraus das Template initialisiert wird. Dies geschieht auch. Jedoch erhalte ich bei einer vorliegenden Installation des Contao-Bootstrap diese Fehlermeldung.
Die Zeilen 63 und 64 waren dann nur ein verzweifelter Versuch das Problem zu lösen. Jedoch ergibt sich auch bei löschen dieser beiden Zeilen das gleiche Problem.

Kann es mit der Reihenfolge zusammenhängen, in welcher die Bundles geladen werden?
Gibt es sonst eine Möglichkeit das Problem zu lösen ?

**Comment by dmolineus** [comment]
Sind dort noch irgendwelche anderen Erweiterungen installiert? Die Erweiterung geht davon aus, dass sich Contao an die dokumentierte Signatur des Hooks hält. 

https://docs.contao.org/books/api/extensions/hooks/parseFrontendTemplate.html

Aus irgendeinen Grund ist dieser aber Null bei dir. Warum und wie dieser gesetzt wird, kann ich bei deinem Beispiel leider nicht erkennen.

**Comment by felix-kaestner** [comment]
Nein. Außer dem Contao-Bootstrap Bundle und dem eigenen Bundle sind keine anderen Erweiterungen installiert. Warum dieser Null als Template setzt ist mir auch ein Rätsel. Innerhalb der Modul-Klasse wird die Variable strTemplate eindeutig gesetzt https://github.com/markenzoo/material-theme-bundle/blob/3dd4a3db775896bd4d5a60def31debd5d6b9f405/material-theme-bundle/src/Resources/contao/modules/NavBarModule.php#L29 . 

Das Modul wird in contao/config.php mittels https://github.com/markenzoo/material-theme-bundle/blob/3dd4a3db775896bd4d5a60def31debd5d6b9f405/material-theme-bundle/src/Resources/contao/config/config.php#L10 eingebunden.

Was ist dabei nicht verstehe ist, das es in einer Contao-Installation ohne das Contao-Bootstrap Bundle problemlos funktioniert. Das FrontEndTemplate wird richtig erzeugt und mir auf der Webseite ausgegeben. Komplett ohne Fehlermeldung. Lediglich im zusammenspiel mit dem Contao-Bootstrap erhalte ich den Fehler, welche die Klasse des Contao-Bootstrap wirft. Leider habe ich bis jetzt keine Lösung gefunden, dieses Problem zu beheben und bin mir auch nicht sicher wo der Fehler liegt.

**Comment by dmolineus** [comment]
> Was ist dabei nicht verstehe ist, das es in einer Contao-Installation ohne das Contao-Bootstrap Bundle problemlos funktioniert.

Das liegt daran, dass ich einen Hook registriert habe, der zwingend voraussetzt, dass der Templatename ein string ist (Strict Types aktiviert). Der Hook ist also der Auslöser. Die Ursache kann irgendwo liegen.

**Comment by dmolineus** [comment]
Fehler liegt nicht am Haupttemplate, sondern am Untertemplate. Eine gescheite IDE sollte dir aber auch anzeigen, wenn die Variable nicht existiert.

```diff
-      $objTemplate = new \FrontendTemplate($navRootTpl);
+      $objTemplate = new \FrontendTemplate($this->navRootTpl);
```
