### ISSUE TITLE
nicht kompatibel mit Contao 4.9.1

### ISSUE THREAD

**Issue by kreativsoehne** [contao-bootstrap/bundle#14]
Auszug aus der Composer-Ausgabe
...
- Conclusion: don't install symfony/security v4.4.5
- Conclusion: don't install contao-bootstrap/bundle 2.1.1
- Conclusion: don't install contao/conflicts dev-master
- Conclusion: don't install contao/conflicts dev-bugfix/knp-time-bundle
...
contao-bootstrap/bundle 2.1.0 requires contao-bootstrap/tab ~2.0 -> satisfiable by contao-bootstrap/tab[2.0.0, 2.0.3, 2.0.4, 2.0.5].
    - contao-bootstrap/tab 2.0.5 requires netzmacht/contao-toolkit ^3.0 -> satisfiable by netzmacht/contao-toolkit[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.3.1, 3.3.2].
    - contao-bootstrap/tab 2.0.4 requires netzmacht/contao-toolkit ^3.0 -> satisfiable by netzmacht/contao-toolkit[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.3.1, 3.3.2].
    - netzmacht/contao-toolkit 3.0.3 requires symfony/security ^3.3 || ^4.0 -> satisfiable by symfony/security[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5].

Vielleicht findet sich da eine Lösung...
Wir freuen uns auf eure Antwort.
Viele Grüße

**Comment by dmolineus** [comment]
Contao-Bootstrap lässt sich problemlos unter Contao 4.9 installieren, entsprechende Vorgehensweise grundsätzlich beachten, https://github.com/contao-bootstrap/tab/issues/8#issuecomment-565487041
