### ISSUE TITLE
Contao 4.11 support

### ISSUE THREAD

**Issue by seibtph** [contao-bootstrap/bundle#19]
Leider lässt sich die Erweiterung nicht unter Contao 4.11 installieren.

Im Contao Manager nach dem Aktualisieren der Pakete erscheint folgende Fehlermeldung:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php on line 32 and at least 1 expected in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
Stack trace:
#0 /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php(32): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Processor.php(50): Netzmacht\Html\Infrastructure\SymfonyBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#2 /www/htdocs/xxx/domains/xxx/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Compon in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php on line 32 and at least 1 expected in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
Stack trace:
#0 /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php(32): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Processor.php(50): Netzmacht\Html\Infrastructure\SymfonyBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#2 /www/htdocs/xxx/domains/xxx/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Compon in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
```

**Comment by ideefixx** [comment]
In Contao 4.12.1 die selbe Störung bei der Installation.

> Leider lässt sich die Erweiterung nicht unter Contao 4.11 installieren.
> 
> Im Contao Manager nach dem Aktualisieren der Pakete erscheint folgende Fehlermeldung:
> 
> ```
> Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php on line 32 and at least 1 expected in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
> Stack trace:
> #0 /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php(32): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
> #1 /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Processor.php(50): Netzmacht\Html\Infrastructure\SymfonyBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
> #2 /www/htdocs/xxx/domains/xxx/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Compon in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
> PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php on line 32 and at least 1 expected in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
> Stack trace:
> #0 /www/htdocs/xxx/domains/xxx/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php(32): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
> #1 /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Processor.php(50): Netzmacht\Html\Infrastructure\SymfonyBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
> #2 /www/htdocs/xxx/domains/xxx/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Compon in /www/htdocs/xxx/domains/xxx/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
> ```

**Comment by dmolineus** [comment]
Aktuell ist die Erweiterung nicht Contao 4.13 kompatibel. Es wurde ein Fundraising gestartet um die Weiterentwicklung sicherzustellen. Mehr Informationen dazu unter https://contao-bootstrap.de/contao-4-13-kompatibilitaet.html
