### ISSUE TITLE
Contao 4 Paket

### ISSUE THREAD

**Issue by csaeum** [contao-bootstrap/bundle#2]
Ab wann kann man mit einen Contao 4.x Paket rechnen?

**Comment by dmolineus** [comment]
Derzeit gibt es noch keine Roadmap. Ursprünglich war geplant mit Bootstrap 4 auch auf Contao 4 umzusteigen. Jedoch scheint die Weiterentwicklung von BS 4 langsam voranzugehen.

**Comment by rflx** [comment]
Anstatt einen RC zu veröffentlichen hat Bootstrap eine Alpha 3 rausgegeben. Wäre nett wenn die Weiterentwicklung seitens von BS ein wenig schneller vorangehen würde. 

Wie schwierig und sinnvoll ist es contao-bootstrap als Symphony bundle rauszugeben das auf Bootstrap 3.3 greift?

**Comment by dmolineus** [comment]
Da die Code-Basis von Contao 3.x in die Jahre gekommen sind, wurde seitens der Community einige Erweiterungen entwickelt, die eine zeitgemäße Architektur bei der Programmierung ermöglichen und auf die contao-bootstrap aufbaut. Problem daran ist, dass diese noch nicht auf Contao 4 portiert wurden. Teilweise sind diese dann auch obsolet, da die neue Symfony Basis die Architektur von Haus aus mitbringt. 

Daher steht man vor der Entscheidung alle 3rd-Party auf Contao 4 zu portieren oder Contao-Bootstrap soweit neu zu entwickeln, dass es die Abhängigkeiten reduziert und dann nur für Contao 4 funktioniert. 

Bisher habe ich auf den Faktor Zeit gesetzt und gehofft, dass nach und nach die entsprechenden Erweiterungen aktualisiert werden. Derzeit ist es noch nicht passiert. Hier fehlt uns in der CCA schlicht die Ressourcen.

Dies betrifft:
- [contao-community-alliance/dependency-container](https://github.com/contao-community-alliance/dependency-container)
- [contao-community-alliance/event-dispatcher](https://github.com/contao-community-alliance/event-dispatcher)
- [contao-community-alliance/meta-palettes](https://github.com/contao-community-alliance/meta-palettes)

Wie man sich auch immer entscheidet, die Investitionen sind nicht gering. Würde man diese für Bootstrap 3 aufbringen, hat man spätestens mit BS 4 den nächsten Break.

**Comment by dmolineus** [comment]
Inzwischen steht ein Paket für Contao 4.4 zur Verfügung
