### ISSUE TITLE
Keine Unterstützung für Contao 5.3 LTS

### ISSUE THREAD

**Issue by taleteller** [contao-bootstrap/bundle#24]
Die Version Contao 5.3 LTS, welche es seit Februar gibt und die alte 4.9 LTS abgelöst hat, wird nicht unterstützt. Zwar ist es möglich das Paket "Bootstrap For Contao Bundle" im Manager auszuwählen, allerdings sie die abhängigen Pakete alle nur für Version 4.4+ verfügbar womit die Installation fehlschlägt. 

Getestet auf einer frischen Instanz von Contao 5.3.

**Comment by dmolineus** [comment]
Für Contao 5 gibt es eine neue Version, die derzeit über ein Early Adopter Programm angeboten wird: https://contao-bootstrap.de/bootstrap-5-verwenden.html
