### ISSUE TITLE
Captcha in Comments are not marked as mandatory

### ISSUE THREAD

**Issue by MacKP** [contao-bootstrap/bundle#3]
There is an span missing and the required Attribute.

Missing span:
`<span class="mandatory">*</span>`

regards

**Comment by dmolineus** [comment]
Notiz für mich: Betrifft netzmacht/contao-form-helper

**Comment by dmolineus** [comment]
@MacKP: Welche Contao Version betrifft dies? Kann dies unter 3.5.15 nicht nachstellen.

**Comment by MacKP** [comment]
Ich hab das Problem hier auf einer 3.5.15. Das Problem ist auch nur beim Captcha. Alle anderen Felder sind passend ausgezeichnet. (auch nach deaktivieren von anderen Erweiterungen kann ich das Problem noch nachstellen).

**Comment by dmolineus** [comment]
Habe es nochmal auf einem extra aufgesetzten Testsystem ausprobiert. Dort kann ich es auch nicht nachvollziehen. Man müsste mal bei der konkreten Installation debuggen.

**Comment by MacKP** [comment]
OK, danke für die Mühe! Ich schließe das Ticket dann erst mal, bis ich eventuell rausbekommen habe wo es zickt...
