### ISSUE TITLE
 Error unexpected '?'

### ISSUE THREAD

**Issue by kabengwa** [contao-bootstrap/bundle#6]
After installing the managed-edition of contao 4.4.7 , with composer 1.5.7. everything was fine until i tried installing contao-bootstrap 2.*  with (composer require contao-bootstrap/bundle 2.*). the error that is being shown in contao var/logs is ;
"[2017-10-24 16:07:38] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /var/www/contao_dev_/vendor/contao-bootstrap/core/src/Environment.php:119)"} []"

**Comment by dmolineus** [comment]
It seems that you don't use PHP 7.1. the Contao manager uses the command line so I guess that's why the PHP versions differ and contao-bootstrap could be installed.

**Comment by kabengwa** [comment]
i actaully do have php 7.1 As you can see here. 
"
PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
"

**Comment by dmolineus** [comment]
Yes, that's what I said. You're using PHP 7.1 on the cli (command line). But you are not using PHP 7.1 with the web server.

Just create a test.php and add following content:

```php
<?php phpinfo(); 
```

**Comment by kabengwa** [comment]
Okay i have seen the php version in the phpinfo it is 7.0. How do i change that to 7.1 if i may ask?

**Comment by dmolineus** [comment]
> Okay i have seen the php version in the phpinfo it is 7.0. How do i change that to 7.1 if i may ask?

You should ask your hoster/provider how to change it.

**Comment by kabengwa** [comment]
i realised i had not updated here. i managed to change the version and now everything is working fine. thank you for the help.
