### ISSUE TITLE
Installation in Contao 4.4.7/ 4.4.8 via CLI

### ISSUE THREAD

**Issue by yoyobo** [contao-bootstrap/bundle#7]
Hallo,

bei der Installation von contao-bootstrap in Contao 4.4.7 oder 4.4.8 über die CLI (Hoster ist Domain Factory) schlägt der Befehl 
`php7.1.6-cli  web/contao-manager.phar.php composer require contao-bootstrap/bundle ~2.0@beta
`
mit folgender Meldung fehl

=====================
[RuntimeException]
An error occurred while executing the "cache:warmup" command: 14:13:50 ERROR     [console] Error thrown while
running command "--ansi cache:warmup --env=prod". Message: "Class contao_bootstrap.core.listener.layout_dca does not exist"
;208m["error" => ReflectionException { …},"comma
nd" => "--ansi cache:warmup --env=prod","message" => "
8;5;113mClass contao_bootstrap.core.listener.layout_dca does not exist"] []
In MetaPalettes.php line 293:

Class contao_bootstrap.core.listener.layout_dca does not exist

======================

Die Installation vorher läuft gut durch, aber der Cache-Warmup klappt dann nicht. Entsprechend taucht das Plugin auch nicht im Backend oder in der GUI vom Contao-Manager auf.

Installation per GUI im Browser ist nicht möglich, da nur per SSH die Memory-Limits von Domain Factory umgangen werden können.

Über Hilfe würde ich mich freuen. Sollten weitere Infos benötigt werden, liefere ich diese gerne.

Viele Grüße
Johannes

**Comment by dmolineus** [comment]
Liege ich richtig in der Annahme dass in der Composer.json `minimum-stability` heruntergesetzt wurde? Ist denn auch `prefer-stable` gesetzt?

Ich vermute, dass du bereits mit symfony 3.4 unterwegs bist, da dort die Services - sie Fehlermeldung besagt dass ein Service nicht gefunden wurde - standardmäßig privat sind.

Da Symfony 3.4 noch nicht released ist, kann der Fehler eigentlich nur bei der vermuteten Konstellation auftreten.

Kurz: prefer-stable: true sollte dein Problem zwischenzeitlich beheben. Den Bug unter S3.4 muss ich noch fixen.

**Comment by yoyobo** [comment]
Hallo,

danke für die schnelle Antwort!
Ich hatte tatsächlich zunächst nur `minimum-stability` auf `dev` gesetzt.
Mit
`    "minimum-stability" : "dev",`
`   "prefer-stable":true`
 funktioniert es aber auch nicht, aber dafür sieht es mit 
`    "minimum-stability" : "beta",`
`   "prefer-stable":true`
gut aus!
Es wurde laut Installations-Log dann auch
`Updating symfony/symfony (3.4.x-dev => v3.3.13): Downloading (100%)`
installiert.
Mit `"minimum-stability" : "dev"` hatte er die falsche Version von Symfony genutzt, was sich dann auch mit deiner Analyse deckt.
Insofern sieht alles erstmal gut aus, danke!


Viele Grüße
Johannes
