### ISSUE TITLE
Installation schlägt fehl bei bundle sowie auch bei core

### ISSUE THREAD

**Issue by csaeum** [contao-bootstrap/bundle#8]
Ich installiere direkt auf der konsole unter php 7.1
beta usw sind in der composer.json gesetzt.

Was ich an dem Fehler nicht verstehe ist das ich ja mit php7.1 arbeite er aber sagt das meine Version nicht reicht.

[InvalidArgumentException]
  Package contao-bootstrap/core at version 2 has a PHP requirement incompatible with your PHP version (7.1.10.0)

wie kann ich das lösen?

**Comment by dmolineus** [comment]
Please use the contao community forum for suppott questions. It's possible to install the bundle/core using php 7.1.

You may have issues with the minimum stability (http://contao-bootstrap.netzmacht.de/neuigkeiten/beta-phase-gestartet.html).
